version: "2"

services:
  web:
    build: ./web-app/
    container_name: "web-app"
    networks:
      - "same"
    restart: "always"
    command: "puma -p 3000 /app/config.ru"
    ports:
      - "3000:3000"
    volumes:
      - "./templates/:/app/assets/templates"
  console:
    build: ./console-app/
    container_name: "console-app"
    networks:
      - "same"
    restart: "always"
    command: "tail -f /var/tmp/file"
    volumes:
      - "./templates/:/templates"
networks:
  same: 