web:
  build: ./web-app/
  restart: "always"
  command: "puma -p 3000 /app/config.ru"
  ports:
    - "3000:3000"
  volumes:
    - "./templates/:/app/assets/templates"
console:
  build: ./console-app/
  restart: "always"
  command: ["ping", "vk.com"]
  volumes:
    - "./templates/:/templates"