source 'https://rubygems.org'

gem 'liquid', '~> 4.0'
gem 'puma'
gem 'rack-app'
gem 'rack-app-front_end'

group :development do
  gem 'pry-byebug'
  gem 'shotgun'
end

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'rack-test'
  gem 'rspec'
  gem 'selenium-cucumber'
  gem 'selenium-webdriver'
end
