# frozen_string_literal: true
source "https://rubygems.org"

gem 'rack-app'
gem 'puma'
gem 'rack-app-front_end'
gem 'liquid', '~> 4.0'

group :development do
  gem 'pry-byebug'
  gem 'shotgun'
end

group :test do
  gem 'rack-test'
  gem 'capybara'
  gem 'rspec', '~> 3.4'
  gem 'selenium-webdriver'
end